minor cleanups
eclipse-vertx/vert.x pull request #3678
Opened 2020-11-29 09:23 UTC by dfa1

- using JDK methods when possible (Arrays.fill, Math.max, Objects.equal)
- diamond operator
- dandling javadoc

2020-11-29 16:43 UTC, julianladisch commented on src/main/java/io/vertx/core/eventbus/impl/HandlerHolder.java
>      return true;
```suggestion
    return Objects.equals(handler, that.handler);
```

2020-11-29 16:58 UTC, julianladisch commented on src/main/java/io/vertx/core/net/impl/SocketAddressImpl.java
>      return true;
```suggestion
    return Objects.equals(host, that.host) && Objects.equals(path, that.path);
```

2020-11-29 16:59 UTC, julianladisch commented on src/main/java/io/vertx/core/net/impl/VertxEventLoopGroup.java
>        return true;
```suggestion
      return Objects.equals(worker, that.worker);
```

2020-11-29 20:39 UTC, dfa1 commented
thank you @julianladisch  for your review. I tried to fix everything you mentioned, please have another look.

2020-11-30 13:13 UTC, tsegismont requested changes
@dfa1thanks, a few concerns

2020-11-30 17:22 UTC, dfa1 commented on src/main/java/io/vertx/core/net/impl/ServerID.java
> +    return Objects.hash(port, host);
thank you @tsegismont :) I just pushed the fix, please have another look

2020-11-30 17:25 UTC, dfa1 commented on src/main/java/io/vertx/core/net/impl/SocketAddressImpl.java
> +    return Objects.hash(port, host, path);
changed to use `Objects.hashCode` that is exactly:

    public static int hashCode(Object o) {
        return o != null ? o.hashCode() : 0;
    }

2020-11-30 21:00 UTC, tsegismont approved these changes
Thank you @dfa1 !

2020-11-30 21:00 UTC, merged