clear set all method when calling with Map.
eclipse-vertx/vert.x pull request #4015
Opened 2021-07-12 18:51 UTC by phillip-kruger

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

Motivation:

See https://github.com/quarkusio/quarkus/issues/18503

When calling `setAll` with a MultiMap, the clear method is called first, but when calling it with Map, it's not.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

2021-07-13 07:24 UTC, vietj commented
thanks @phillip-kruger can you add a test for this ?

2021-07-13 07:26 UTC, phillip-kruger commented
@vietj - on it.

2021-07-13 07:53 UTC, phillip-kruger commented
@vietj - I added test cases. 
Please confirm that I am correct as I am not sure that it's suppose to work like this. Basically, I am trying to get `setAll(MultiMap)` and `setAll(Map)` work the same way (clear the map first).
Thanks

2021-07-13 14:40 UTC, vietj commented
@phillip-kruger I think this is correct to clear the multimap first, and setAll a map<String, String> can be reduced to setAll a mmap

2021-07-13 14:53 UTC, vietj commented
no, that would be sub optimal I think

On Tue, Jul 13, 2021 at 4:47 PM Phillip Krüger ***@***.***> wrote:
>
> Ok cool. Do you want me to change the code so that the setAll(Map) method just create a multimap and call the setAll(MultiMap) method ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-08-05 10:00 UTC, vietj commented
looking again at this @phillip-kruger , the operations that require a clear are on `MultiMap`, so the added tests should be in`HeadersTestBase` and not in `VertxHttpHeadersTest`

2021-08-05 10:00 UTC, vietj requested changes
looking again at this @phillip-kruger , the operations that require a clear are on `MultiMap`, so the added tests should be in`HeadersTestBase` and not in `VertxHttpHeadersTest`

2021-08-05 11:05 UTC, phillip-kruger commented
Hi @vietj - I moved the tests. Let me know.

2021-08-05 16:23 UTC, vietj commented
excellent @phillip-kruger it will be merged soon and back-ported to 4.1

2021-08-06 07:13 UTC, merged