Allow NetClient to propagate an externally supplied SSLContext to the…
eclipse-vertx/vert.x pull request #4375
Opened 2022-05-16 15:16 UTC by kabir

… SSLHelper

If an external SSLContext is passed to the SSLHelper, it will be used
to create the SSLEngine. In other words the SSLContext will take
precendence over the parts of NetClientOptions traditionally used to
create the SSLEngine.

Motivation:

As discussed with @vietj we need to be able to pass in an SSLContext when running the clients in WildFly. If one is passed in, that takes over creation of the SSLEngine. Currently Vert.x creates the SSLEngine from a specified truststore etc.

Conformance:
I've signed the agreement (and adjusted to sign the commits after opening the initial PR)

2022-05-20 15:37 UTC, cescoffier commented
@kabir can you check the test failures to verify if they are related?

2022-05-23 10:36 UTC, kabir commented
@cescoffier I've looked and I don't think they are related. The new code path should only be triggered by the added test.

I've tried to verify locally, and I can't get a clean run here on the master branch. With a plain `mvn clean install` I get 

Failed tests: 
  Http2ClientTest.lambda$testResponseCompression$192:1379->AsyncTestBase.assertEquals:360 expected:<deflate, gzip[, br]> but was:<deflate, gzip[]>
Tests in error: 
  Http1xBrotliCompressionTest>AsyncTestBase.before:78->HttpCompressionTestBase.setUp:79->HttpCompressionTestBase.compress:61->encoder:22 » NoClassDefFound
  Http1xBrotliCompressionTest>AsyncTestBase.before:78->HttpCompressionTestBase.setUp:79->HttpCompressionTestBase.compress:61->encoder:22 » NoClassDefFound
  Http1xBrotliCompressionTest>AsyncTestBase.before:78->HttpCompressionTestBase.setUp:79->HttpCompressionTestBase.compress:61->encoder:22 » NoClassDefFound
  Http1xBrotliCompressionTest>AsyncTestBase.before:78->HttpCompressionTestBase.setUp:79->HttpCompressionTestBase.compress:61->encoder:22 » ExceptionInInitializer
  Http1xBrotliCompressionTest>AsyncTestBase.before:78->HttpCompressionTestBase.setUp:79->HttpCompressionTestBase.compress:61->encoder:22 » NoClassDefFound
  Http2BrotliCompressionTest>AsyncTestBase.before:78->HttpCompressionTestBase.setUp:79->HttpCompressionTestBase.compress:61->encoder:22 » NoClassDefFound
  Http2BrotliCompressionTest>AsyncTestBase.before:78->HttpCompressionTestBase.setUp:79->HttpCompressionTestBase.compress:61->encoder:22 » NoClassDefFound
  Http2BrotliCompressionTest>AsyncTestBase.before:78->HttpCompressionTestBase.setUp:79->HttpCompressionTestBase.compress:61->encoder:22 » NoClassDefFound
  Http2BrotliCompressionTest>AsyncTestBase.before:78->HttpCompressionTestBase.setUp:79->HttpCompressionTestBase.compress:61->encoder:22 » NoClassDefFound
  Http2BrotliCompressionTest>AsyncTestBase.before:78->HttpCompressionTestBase.setUp:79->HttpCompressionTestBase.compress:61->encoder:22 » NoClassDefFound

Tests run: 5012, Failures: 1, Errors: 10, Skipped: 20

This happens both on master and on my PR branch

2022-05-24 08:28 UTC, vietj commented
can you rebase on latest master, this comes from the netty version bump @kabir

2022-05-24 08:45 UTC, kabir commented
@vietj Rebased (although I believe for my local testing yesterday I already had the netty version)

2022-05-25 10:24 UTC, kabir commented
@vietj @cescoffier I think one of you needs to trigger CI again since I am a first time contributor

2022-05-25 12:41 UTC, vietj commented
done @kabir

2022-05-30 07:38 UTC, vietj commented on src/main/java/io/vertx/core/net/impl/NetClientImpl.java
> +  @Deprecated
no need for deprecated here as it's impl

2022-05-30 07:40 UTC, vietj requested changes
Simply remove `@deprecated` annotation, it's not necessary for internal APIs.

2022-05-30 08:46 UTC, kabir commented
@vietj done :-)

2022-05-30 09:41 UTC, vietj commented on src/main/java/io/vertx/core/net/impl/NetClientImpl.java
> +  @Deprecated
still a deprecation here @kabir

2022-05-30 12:05 UTC, kabir commented
@vietj Sorry about that - I think I've removed all @Deprecated now

2022-05-31 08:31 UTC, merged