Remove CLI usage in Vert.x Core (examples and code)
eclipse-vertx/vert.x pull request #4769
Opened 2023-07-06 16:47 UTC by tsegismont

Commits can be reviewed individually

2023-07-07 17:19 UTC, vietj commented
it seems this PR removes more than just examples, so I'm guessing we need to wait until this is resurrected in vertx-launcher to merge it to avoid vertx-shell breaking

2023-07-27 08:29 UTC, vietj commented on src/main/java/io/vertx/core/AbstractVerticle.java
> +   *
the Java doc should be changed to : "returns an empty list"

2023-07-27 08:30 UTC, vietj commented on src/main/java/io/vertx/core/Context.java
> +   * @deprecated As of version 5, Vert.x is no longer tightly coupled to the CLI
should also say that now it returns an empty list

2023-07-27 08:35 UTC, vietj requested changes
Couple of minor changes, but LGTM

2023-07-28 07:00 UTC, tsegismont commented
@vietj done

2023-08-01 06:08 UTC, merged